runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /static/images.*
  static_dir: static/images
- url: /static/Fonts.*
  static_dir: static/Fonts
- url: /static.*
  static_dir: static
- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
