runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/landing.html
  upload: static/landing.html
- url: /static.*
  static_dir: static
- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
